#!/usr/bin/env python3
"""
Test script for post-print auto-deduction
Tests both successful prints (footer data) and failed prints (header-only data)
"""

import os
import subprocess
import sys
import tempfile
from pathlib import Path

print("=" * 70)
print("Testing Auto-Deduct Script - Complete Print vs Failed Print")
print("=" * 70)
print()

# Test 1: Complete print with ACTUAL usage in footer
print("TEST 1: Complete Print (actual usage in footer)")
print("-" * 70)

test_gcode_complete = """
; ===== HEADER (Estimated Usage) =====
; generated by PrusaSlicer 2.6.0 on 2024-10-15
; filament_type = PLA
; filament_colour = Translucent
; filament_vendor = ATA
; filament used [g] = 25.50
; filament used [cm3] = 20.56
; estimated printing time = 3h 15m

G28 ; home all axes
G1 Z5 F5000
M104 S200
M140 S60
; ... print moves ...

; ===== FOOTER (Actual Usage) =====
; Print completed successfully
; Total print time: 3h 12m 45s
; filament used [g] = 24.80
; filament used [cm3] = 20.00
M104 S0
M140 S0
G28 X0
M84
"""

with tempfile.NamedTemporaryFile(mode='w', suffix='.gcode', delete=False) as f:
    f.write(test_gcode_complete)
    gcode_complete_path = f.name

print(f"Created test G-code: {gcode_complete_path}")
print()

# Run test for complete print
os.environ['FILAMENT_POSTPRINT_LOG'] = '1'

script_dir = Path(__file__).parent
postprint_script = script_dir / 'postprint_usage.py'

result1 = subprocess.run(
    [sys.executable, str(postprint_script), gcode_complete_path],
    capture_output=True,
    text=True
)

print("Output:")
print(result1.stdout)
if result1.stderr:
    print("Errors:", result1.stderr)

# Clean up
try:
    os.unlink(gcode_complete_path)
except OSError:
    pass

if "24.80" in result1.stdout or "24.8" in result1.stdout:
    print("✅ PASS: Used ACTUAL footer data (24.80g), not estimate (25.50g)")
else:
    print("❌ FAIL: Did not use footer data correctly")

print()
print("=" * 70)
print()

# Test 2: Failed print with NO footer data (should use header estimate with warning)
print("TEST 2: Failed Print (no footer data, using header estimate)")
print("-" * 70)

test_gcode_failed = """
; ===== HEADER ONLY (Estimated Usage) =====
; generated by PrusaSlicer 2.6.0 on 2024-10-15
; filament_type = PLA
; filament_colour = Translucent
; filament_vendor = ATA
; filament used [g] = 25.50
; filament used [cm3] = 20.56
; estimated printing time = 3h 15m

G28 ; home all axes
G1 Z5 F5000
M104 S200
M140 S60
; ... print moves (stopped early due to failure) ...

; Print aborted or failed - no footer statistics
M104 S0
M140 S0
M84
"""

with tempfile.NamedTemporaryFile(mode='w', suffix='_failed.gcode', delete=False) as f:
    f.write(test_gcode_failed)
    gcode_failed_path = f.name

print(f"Created test G-code: {gcode_failed_path}")
print()

result2 = subprocess.run(
    [sys.executable, str(postprint_script), gcode_failed_path],
    capture_output=True,
    text=True
)

print("Output:")
print(result2.stdout)
if result2.stderr:
    print("Errors:", result2.stderr)

# Clean up
try:
    os.unlink(gcode_failed_path)
except OSError:
    pass

if "WARNING" in result2.stdout and ("25.50" in result2.stdout or "25.5" in result2.stdout):
    print("✅ PASS: Used header estimate (25.50g) with WARNING about assumption")
else:
    print("❌ FAIL: Did not handle missing footer data correctly")

print()
print("=" * 70)
print()
print("SUMMARY:")
print("-" * 70)
print("Test 1 (Complete): Should use ACTUAL footer data (24.80g)")
print("Test 2 (Failed):   Should use ESTIMATED header data (25.50g) with WARNING")
print()
print("This ensures:")
print("  • Successful prints = accurate deduction from footer")
print("  • Failed prints = conservative estimate from header")
print()
print("To check detailed logs:")
log_path = Path.home() / '.filament-inventory' / 'postprint.log'
print(f"  {log_path}")
print()

if result1.returncode == 0 and result2.returncode == 0:
    print("✅ All tests PASSED!")
else:
    print("❌ Some tests FAILED - check output above")
